import pygetwindow as gw

# Window Dimensions for pygame 

MONITOR_SCREEN = gw.getActiveWindow()
MONITOR_WIDTH = MONITOR_SCREEN.width
MONITOR_HEIGHT = MONITOR_SCREEN.height

WINDOW_WIDTH = MONITOR_WIDTH * 0.6
WINDOW_HEIGHT = MONITOR_HEIGHT * 0.6


# print(WINDOW_WIDTH, WINDOW_HEIGHT)