import pygetwindow as gw

# Monitor Dimensions
MONITOR_SCREEN = gw.getActiveWindow()
MONITOR_WIDTH = MONITOR_SCREEN.width
MONITOR_HEIGHT = MONITOR_SCREEN.height

# Window Dimensions
WINDOW_WIDTH = MONITOR_WIDTH * 0.75
WINDOW_HEIGHT = MONITOR_HEIGHT * 0.75

WINDOWN_HALF_WIDTH = WINDOW_WIDTH * 1/2
WINDOW_HALF_HEIGHT = WINDOW_HEIGHT * 1/2